twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: true
  exception_controller: null
  globals:
    flash: '@App\Shared\Infrastructure\Symfony\FlashSession'
    attachment: '@App\Shared\Infrastructure\Symfony\Attachment'
    socialShareURLs: '@App\Shared\Infrastructure\Symfony\SocialShareURLs'
